[project]
name = "py-collections"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pydantic>=2.11.7",
    "pytest>=8.4.1",
    "pytest-sugar>=1.1.1",
]
